# required for building jre_lwjgl3glfw with Java 8 while using plugins in app_pojavlauncher that require Java 11
org.gradle.configureondemand=true

android.useAndroidX=true
android.bundle.language.enableSplit=false
# Increase Gradle daemon RAM allocation
org.gradle.jvmargs=-Xmx4096M
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.suppressUnsupportedCompileSdk=37.0
android.enableR8.fullMode=false
VERSION_CODE=9
VERSION_NAME=4.0.6
