pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven { url "https://jitpack.io" }
        flatDir {
            dirs 'app_pojavlauncher/libs'
        }
    }
}

rootProject.name='HyperLauncher'
include ':app_pojavlauncher'

include ':forge_installer'
include ':glfw:android-gradle'
include ':ColorPicker'
include ':MioLibPatcher'
